title: Jekylly
tagline: Community driven Jekyll tutorials and themes.
author: Kyle Kirkby
url: "https://jekylly.com"
email: kylekirkbyy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A GitHub community driven Jekyll tutorial hub which aims to give the web
  development community the detailed and up to date knowledge for building
  awesome Jekyll static websites.

twitter_username: jekyllykej
github_username:  jekylly
permalink: /blog/:title/
carousel_params:
  - one
  - two
  - three
  - four
  - five
  - six
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

highlighter: rouge

plugins:
  - jekyll-assets
  - uglifier

include:
  - content

exclude:
  - manifest.json
  - .htaccess
assets:
  destination: "/assets"
  compression: true
  gzip: true
  sources:
    - assets/css
    - assets/js
    - assets/img
    - _sass

pagination:
  paginate_path: /blog/:num/

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - Page :num'

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'


 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
